mbe/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings
from member import urls as member_urls
from collection import urls as collection_urls
from page import views as page_views
from mbe import views as mbe_views
from wish import urls as wish_urls
urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^account/', include(member_urls)),
    url(r'^wish/', include(wish_urls)),
    url(r'^p/',include(collection_urls)),
    url(r'^$', mbe_views.home, name = 'Home' ),
    url(r'^index/$',mbe_views.home, name = 'Home'),
    url(r'^collection/', page_views.get_collection_page, name = 'The Collection' ),
    url(r'^mbe/', page_views.get_about_page, name = 'About Us' ),
    url(r'^contact/', mbe_views.contact, name = 'Contact Us' ),
    url(r'^commitments/', mbe_views.commitments, name = 'Our Commitments' ),
    url(r'^conditions/', mbe_views.conditions, name = 'General Conditions' ),
]+static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

member/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class Member(models.Model):
	user = models.OneToOneField(User, on_delete = models.CASCADE)
	email1 = models.EmailField(blank = True, null = True, verbose_name = "Friend's email" )
	kidsname = models.CharField(max_length = 128, verbose_name = "Kids' names", blank = True, null = True)
	address = models.TextField(verbose_name = 'Address', blank = True, null = True)

	class Meta:
		verbose_name = 'Member'
		verbose_name_plural = 'Member'

	def __unicode__(self):
		return self.user.username

templates/base.html
<!DOCTYPE html>
<html lang="zh-CN">
<head>
	<meta charset= "utf-8">
	<meta name="author" content="MBE & Jaz">
	<meta name="description" content = "">
	<link rel="stylesheet" type="text/css" href="/static/materialize/css/materialize.min.css">
	<link rel="stylesheet" type="text/css" href="/static/mbe/css/style.css">
	<link rel="stylesheet" type="text/css" href="/static/fa/css/font-awesome.min.css">
	<title>{% block title %}{% endblock %}</title>
{% block css %}
{% endblock %}
</head>
<body>
<div id="wrap">
<header>
	<div class="topbar">
		<ul>
		<li><a href="/account/profile/">MY ACCOUNT</a></li>
		{% if request.user.is_authenticated %}
		<li><a>|</a></li>
		<li><a href="/account/logout/">LOGOUT</a>
		{% endif %}
		</ul>
	</div>
	<div class="navbar">
		<ul class="nav-left">
			<li><a href="/mbe/">MBE</a></li>
			<li><a href="/p/newborn/">NEW BORN</a></li>
			<li><a href="/p/girl/">GIRL</a></li>
		</ul>
		<a href="/" class="logo"><img src="/static/mbe/images/logo.png"/ width="100px"></a>
		<ul class="nav-right">
			<li><a href="/p/boy/">BOY</a></li>
			<li><a href="/p/accessories/">ACCESSORIES</a></li>
			<li><a href="/wish/">MAKE A WISH</a></li>
		</ul>
	</div>
	{% block subnav %}
	{% endblock %}
</header>
<main>
	{% block content %}
	{% endblock %}
</main>
</div>
<footer>
	<ul>
		<li><a href="/contact/" class="black-text">CONTACT</a></li>
		<li><a href="/commitments/" class="black-text">OUR COMMITMENTS</a></li>
		<li><a href="/conditions/" class="black-text">GENERAL CONDITIONS</a></li>
	</ul>
</footer>
</body>
<script type = "text/javascript" src="/static/mbe/js/jquery.min.js"></script>
<script type="text/javascript" src="/static/materialize/js/materialize.min.js"></script>
{% block js %}
{% endblock %}

templates/commitments.html
{% extends 'base.html' %}
{% block title %}Our Commitments{% endblock %}
{% block content %}
<main>
	<div class="content container commitments">
		<div class="row">
		<div class="col s12 cover">
			<img src="{{ page.cover.url }}" class="responsive-img">
		</div>
		</div>
		<div class="row">
		<div class="col s12">

			<h6>QUALITY GUARANTEE</h6>
			<p>1. Ma Belle Epoque sells exclusively refined and high quality products. These products are directly designed and produced by Ma Belle Epoque, carefully selecting materials by stringent quality controls.</p>
			<p>2. Ma Belle Epoque does not sell second-hand products, flawed products or products of lower quality as compared to the corresponding standards offered on the market.</p>
			<p>3. The main characteristics of the products are shown on www.mabelleepoque.com inside each product description. The products offered for sale on www.mabelleepoque.com may not exactly correspond to the real garments in terms of image and colours because of the Internet browser or the monitor used.</p>

			<h6>SIZES</h6>
			<table class="bordered responsive-table ">
				<thead>
					<tr>
						<th>Size</th>
						<th>Chest</th>
						<th>Waist</th>
						<th>Height</th>
					</tr>
				</thead>
				<tbody>
					<tr>
						<td>3 months</td>
						<td>41cm</td>
						<td>43cm</td>
						<td>54cm</td>
					</tr>
					<tr>
						<td>6 months</td>
						<td>43cm</td>
						<td>46cm</td>
						<td>66cm</td>
					</tr>
					<tr>
						<td>1 year</td>
						<td>46cm</td>
						<td>48cm</td>
						<td>76cm</td>
					</tr>
					<tr>
						<td>2 years</td>
						<td>54cm</td>
						<td>53cm</td>
						<td>92cm</td>
					</tr>
					<tr>
						<td>3 years</td>
						<td>55cm</td>
						<td>54cm</td>
						<td>98cm</td>
					</tr>
					<tr>
						<td>4 years</td>
						<td>57cm</td>
						<td>55cm</td>
						<td>104cm</td>
					</tr>
				</tbody>
			</table>

			<h6>RAPID DELIVERY</h6>

			<p>We provide a standard delivery service:</p>
			<ul>
			<li>· UK mainland - £6 | 1- 3 days</li>
			<li>· Europe - £10 | 3 - 4 days</li>
			<li>· Rest of world - £15 | 7 days</li>
			</ul>
			<br/>
			<p>International shipping - Ma Belle Epoque delivers all over the world.</p>
			<br/>
			<p>If you would like to place your order by phone our customer service department will be happy to assist you. You can contact our customer service department at +44(0)7913059428 or +44 7484 132145</p>

		</div>
		</div>
	</div>
</main>
{% endblock %}

templates/conditions.html
{% extends 'base.html' %}
{% block title %}Our Commitments{% endblock %}
{% block content %}
<main>
	<div class="content container conditions">
		<div class="row">
		<div class="col s12 cover">
			<img src="{{ page.cover.url }}" class="responsive-img">
		</div>
		</div>
		<div class="row">
		<div class="col s12">
<h6>MAKING A PURCHASE</h6>

<p>1. Our website displays information on the main characteristics of each product and the relevant unit price, the type of payment that you may use in order to purchase each product, shipping and delivery costs, the terms and conditions for the return of purchased products and, finally, the methods and time periods for returning the products purchased.</p>
<p>2. After your order form has been submitted, Ma Belle Epoque will process your order.</p>
<p>3. If unfortunately the products displayed on <a href="/">www.mabelleepoque.com</a> are no longer available at the time of your last login to our online store, Ma Belle Epoque shall inform you within five working days. If the order form has been sent and the price has been paid for items that are no longer available, Ma Belle Epoque will refund you the sum paid.</p>



<h6>DELIVERIES</h6>
<p>Details of delivery charges below. Orders are sent using one of our preferred shipping partners and tracking information is available</p>
<ul>
<li>· UK mainland - £6 | 1- 3 days</li>
<li>· Europe - £10 | 3 - 4 days</li>
<li>· Rest of world - £15 | 7 days</li>
</ul>



<h6>SHIPPING & RETURNS</h6>

<p>1. You have the opportunity to return any product ordered at Ma Belle Epoque within fourteen days following the day your products were received in its original packaging. Return charges are to be paid by the customer.</p>
<p>2. The refund will be made in the same way that the product was originally purchased.</p>
<p>3. Ma Belle Epoque will not accept returned products that are returned without their original packaging or that have been altered from their original status or damaged.</p>

<h6>WISH LIST</h6>

<p><a href="/">www.mabelleepoque.com</a> is the perfect place to buy someone a present. It has a Wish List section where you can see what your friends “wished for" and surprise them with it when preparing their new born’s trousseau.</p>
<p>It is very easy to do, select a product and enter the person's address as the delivery address on our online store. A personalised message can also be attached to the package if you wish. Of course, the package will be carefully wrapped with our usual high standards.</p>

<h6>SECURE PAYMENT</h6>

<p>Ma Belle Epoque website operates with Visa and Paypal so as to ensure maximum security in the course of transactions via the websites.</p>

<h6>PRIVACY</h6>
<p>1. You can use mabelleepoque.com site without giving out any personal information. However, when you create an account on <a href="/"><a href="/">www.mabelleepoque.com</a></a> we will collect the necessary information relative to the invoicing and shipping of your order.</p>
<p>2. You can also share on <a href="/">www.mabelleepoque.com</a> your friends’ emails address for us to reach out to them and “make your wish come true” when your little one comes to the world.</p>
<p>3. <a href="/">www.mabelleepoque.com</a> website will only share your personal information when it is necessary for the processing of your order: bank, courier partner etc. mabelleepoque.com will use this information when it is necessary to identify you but under no other circumstances Ma Belle Epoque will use your information for other purposes.</p>


		</div>
		</div>
	</div>
</main>
{% endblock %}

templates/contact.html
{% extends 'base.html' %}
{% block title %}Contact Us!{% endblock %}
{% block content %}
<main>
	<div class="content container contact">
		<div class="col s12 cover">
			<img src="{{ page.cover.url }}" class="responsive-img">
		</div>
		<h4 class="text">CONTACTS</h4>
		<h6>YOUR MESSAGE</h6>
		  <div class="row">
		    <form class="col s12" method = "POST" action = "/contact/">
		    {% csrf_token %}
		      <div class="row">
		        <div class="input-field col s6">
		          <div class="label">FIRST NAME</div>
		          <input id="id_firstname" name = 'firstname' type="text" class="validate">
		        </div>
		        <div class="input-field col s6">
		          <div class="label">LAST NAME</div>
		          <input id="id_lastname" name = 'lastname' type="text" class="validate">
		        </div>
		      </div>
		      <div class="row">
		        <div class="input-field col s6">
		          <div class="label">PHONE NUMBER</div>
		          <input id="id_phone" type="tel" name = 'phone' class="validate">
		        </div>
		        <div class="input-field col s6">
		          <div class="label">E-MAIL ADDRESS*</div>
		          <input id="id_email" type="email" name = 'email' class="validate">
		        </div>
		      </div>
		      <div class="row">
		        <div class="input-field col s6">
		          <div class="label">SUBJECT*</div>
		          <input id="id_subject" name = 'subject' type="text" class="validate">
		        </div>
		      </div>

				<div class="row">
				<div class="input-field col s12">
				  <div class="label">MESSAGE*</div>
				  <textarea id="id_textarea1" name = 'content' class="materialize-textarea validate"></textarea>
				</div>
				</div>
		      <div class="row right">
			      	<input type = "submit" id = "submit" class="btn btn-large btn-reverse right" value ="submit" />
		      </div>
		    </form>
		  </div>
		  <div class="row">
		  	<p class="col s12 tip">ANY QUESTIONS? Contact our <span style="color:#E2BF00;">CUSTOMER SERVICE</span> T. +447913059428 or +44 7484 132145</p>
		  </div>
	</div>
</main>
</div>
{% endblock %}

templates/index.html
<!DOCTYPE html>
<html lang="zh-CN">
<head>
	<meta charset= "utf-8">
	<meta name="author" content="MBE & Jaz">
	<meta name="description" content = "">
	<link rel="stylesheet" type="text/css" href="static/materialize/css/materialize.min.css">
	<link rel="stylesheet" type="text/css" href="static/mbe/css/style.css">
	<link rel="stylesheet" type="text/css" href="static/fa/css/font-awesome.min.css">
	<link rel="stylesheet" type="text/css" href="static/vegas/vegas.min.css">
	<title>index</title>
</head>
<body>
<div id = "wrap">
<header>
	<div class="topbar">
		<ul>
		<li><a href="/account/profile/" class="white-text">MY ACCOUNT</a></li>
		{% if request.user.is_authenticated %}
		<li><a>|</a></li>
		<li><a href="/account/logout/" class="white-text">LOGOUT</a>
		{% endif %}
		</ul>
	</div>
	<div class="navbar container ">
		<a href="/" class="logo"><img src="static/mbe/images/logo-white.png" class="responsive-img" width="150px;"></a>
	</div>
</header>
<main>
	<div class="index container">
		<h3 class="main_title">
			{{ c.name }}
		</h3>
		<a href="/collection/" class="btn-large btn">Discover</a>
	</div>
</main>
</div>
<footer id="footer-index">
	<ul>
		<li><a href="/contact/" class="white-text">CONTACT</a></li>
		<li><a href="/commitments/" class="white-text">OUR COMMITMENTS</a></li>
		<li><a href="/conditions/" class="white-text">GENERAL CONDITIONS</a></li>
	</ul>
</footer>
</body>
<script text = "text/javascript" src="static/mbe/js/jquery.min.js"></script>
<script type="text/javascript" src="static/materialize/js/materialize.min.js"></script>
<script src="static/vegas/vegas.min.js"></script>
<script type="text/javascript">
	$("body").vegas({
    slides: [
        { src: "{{ c.background.url }}" },
    ]
});
</script>

templates/login.html
{% extends 'base.html' %}
{% block title %}Login{% endblock %}
{% block content %}
	<div class="content container login">
		<div class="row">
			<div class="col s3 offset-l1">
				<img src="{{ page.cover.url }}" class="responsive-img">
			</div>
			<div class="col s6 offset-l1" >
			   <form class="col s12" style="margin-top:100px;" method="POST" action = "/account/login/">
			   {% csrf_token %}
			   	  {% if error %}
			   	  <div class="row error">
			   	  	{{ error }}
			   	  </div>
			   	  {% endif %}
			      <div class="row">
			        <div class="input-field col s12">
			          <div class="label" >Username</div>
			          <input id="id_username" type="text" class="validate" name = "username">
			        </div>
			      </div>
			      <div class="row">
			        <div class="input-field col s12">
			          <div class="label" >Password</div> 
			          <input id="id_password" type="password" class="validate" name = "password">
			        </div>
			      </div>
			      <div class="row panel">
			      	<a class="new left" href="/account/register/">Create A New Account</a>
			      	<input type = "submit" id = "submit" class="btn btn-large btn-reverse right" value ="submit"></>
			      </div>
			    </form>
			</div>
		</div>
	</div>
{% endblock %}
{% block js %}
<script type="text/javascript">
	$("#submit").click(function(){
		$("form").submit();
	});
</script>
{% endblock %}

templates/page.html
{% extends 'base.html' %}
{% block title %}{{ page.name }}{% endblock %}
{% block content %}
	<div class="content container lookbook">
		<div class="cover">
			<h2>{{ page.name }}</h2>
			<img src="{{ page.cover.url }}" class="responsive-img">
		</div>
		<div class="row">
			<div class="col s6 col-left">
				{% for s in left_sections %}
					{% if s.stype == 'text' %}
					<div class="col-text">
						<h3>{{ s.title }}</h3>
						<p>{{ s.content|linebreaksbr }}</p>
					</div>
					{% else %}
					<figure class="col-image">
						<img src="{{ s.image.url }}" class="responsive-img" />
					</figure>				
					{% endif %}
				{% endfor %}
			</div>
			<div class="col s6 col-right">
				{% for s in right_sections %}
					{% if s.stype == 'text' %}
					<div class="col-text">
						<h3>{{ s.title }}</h3>
						<p>{{ s.content|linebreaksbr }}</p>
					</div>
					{% else %}
					<figure class="col-image">
						<img src="{{ s.image.url }}" class="responsive-img" />
					</figure>				
					{% endif %}
				{% endfor %}
			</div>
		</div>
	</div>
{% endblock %}

templates/product.html
{% extends "base.html" %}
{% block title %}
{{ category.name }}
{% if subcategory %}
|{{ subcategory.name }}
{% endif %}
{% endblock %}
{% block subnav %}
	<div class="sub-nav">
		<ul>
			{% for c in category.subs.all %}
			<li><a href="/p/{{ category.slug }}/{{ c.slug }}/">{{ c.name }}</a></li>
			{% endfor %}
		</ul>
	</div>
{% endblock %}
{% block content %}
	<div class="content container product">
		<div class="row">
			<div class="col s12 cover">
				<img src="{{ category.cover.url }}" class="responsive-img">
			</div>
		</div>
		<div class="row">
			<div class="row" style="margin:0;padding:0">
			<div class="col s6">
				<div class="cate">
					<h3>{{ category.page_title }}</h3>
					<p>{{ category.description|linebreaksbr }}</p>
				</div>
			</div>
			<div class="col s6">
				<img src = "{{ category.image.url }}" class="responsive-img">
			</div>
			</div>
			{% for p in products %}
			<div class="col s6 p">
				<div class="cover">
					<img src="{{ p.image1.url }}" class="responsive-img" data="{{ p.image2.url }}">
				</div>
				<div class='row'>
				<div class="panel col s11">
					{% if p.wishes.all.count != 0 %}
					<div class="col s12 tip">
						{% if request.user.is_authenticated and request.user in users %}
						Wished by you and&nbsp;<a href="/wish/">{{ p.wishes.all.count }}</a> &nbsp;friends 
						{% else %}
						Wished by &nbsp;<a href="/wish/">{{ p.wishes.all.count }}</a> &nbsp;friends
						{% endif %}
					</div>
					{% else %}
					<div class="col s12 tip">
					    Click on the flower to make your wish come true
					</div>
					{% endif %}
					<div class="col s12 text">
						<span class="col s12 ">
							<b>{{ p.name }}</b>
						</span>
						<span class="col s12 ">
						{{ p.short_description }}
						</span>
						<span class="col s12 ">
							¥{{ p.price }}
						</span>
					</div>
				</div>
				<div class="col s1 like">
				{% if request.user.is_authenticated and request.user in p.get_wished_users %}
					<a href="/wish/remove/?pid={{ p.id }}&next={{ request.get_full_path }}" class="valign-wrapper"><img src="/static/mbe/images/flower.png" class="responsive-img"  /></a>						
				{% else %}
					<a href="/wish/add/?pid={{ p.id }}&next={{ request.get_full_path }}" class="valign-wrapper"><img src="/static/mbe/images/flower.png" class="responsive-img"  /></a>
				{% endif %}
				</div>	
				</div>
			</div>
			{% endfor %}
		</div>
	</div>
{% endblock %}
{% block js %}
<script type="text/javascript">
	$(".cover").mouseover(function(){
		var src = $(this).find("img").attr("src");
		var data = $(this).find("img").attr("data");
		$(this).find("img").attr("src",data);
		$(this).find("img").attr("data",src);
	}).mouseleave(function(){
		var src = $(this).find("img").attr("src");
		var data = $(this).find("img").attr("data");
		$(this).find("img").attr("src",data);
		$(this).find("img").attr("data",src);		
	});
  $(document).ready(function(){
    // the "href" attribute of .modal-trigger must specify the modal ID that wants to be triggered
    $('.like').click(function(){
    	$(this).parents('.p').children('.tip').children('span').text('You');
    });
  });</script>
  {% endblock %}

templates/register.html
{% extends 'base.html' %}
{% block title %}Create a new user{% endblock %}
{% block content %}
	<div class="content container register">
		<div class="row">
			<div class="col s5">
				<img src="{{ page.cover.url }}" class="responsive-img">
			</div>
			<div class="col s6 offset-l1">
			<h3 class="text">JOIN US!</h3>
			   <form class="col s12" id ="multipart" action = "/account/register/" enctype="multipart/form-data" method="POST">
			      {% csrf_token %}
			      <div class="row">
			        <div class="input-field col s12">
			          <div class="label">USERNAME</div>
			          <input id="id_username" name = "username" type="text" class="validate" value = '{{ user_form.username.value|default_if_none:"" }}'>
			        </div>
			        	{{ user_form.username.errors }}
			        
			      </div>
			      <div class="row">
			        <div class="input-field col s12">
			        <div class="label">PASSWORD</div>
			          <input id="id_password" name = "password" type="password" class="validate">         
			        </div>
			         {{ user_form.password.errors }}
			      </div>
			      <div class="row">
			        <div class="input-field col s12">
			        <div class="label">E-MAIL</div>
			          <input id="id_email" type="email" name = "email" class="validate" value = '{{ user_form.email.value|default_if_none:"" }}'>
			        </div>
			        {{ user_form.email.errors }}
			      </div>
			      <div class="row">
			        <div class="input-field col s12">
			        <div class="label">KIDS'NAMES</div>
			          <input id="id_kidsname" type="text" name = "kidsname" class="validate" value = '{{ member_form.kidsname.value|default_if_none:"" }}'>
			        </div>
			      </div>
			      <div class="row">
			        <div class="input-field col s12">
			        <div class="label">FRIEND'S E-MAIL</div>
			          <input id="id_email1" type="email" name = "email1" class="validate" placeholder = 'Let your friends make your wish come true' value = '{{ member_form.email1.value|default_if_none:"" }}'>
			        </div>
			        {{ member_form.email1.errors }}
			      </div>
			      <div class="row">
			        <div class="input-field col s12">
			        <div class="label">ADDRESS</div>
			          <textarea id="id_address" name = "address" class="materialize-textarea validate">{{ member_form.address.value|default_if_none:"" }}</textarea>
			        </div>
			      </div>
			      <div class="row right">
			      	<a href="#!" class="btn btn-large btn-reverse" id = "submit">SUBMIT</a>
			      </div>
			    </form>
			</div>
		</div>
	</div>
{% endblock %}
{% block js %}
<script type="text/javascript">
	$("#submit").click(function(){
		$("form").submit();
	});
</script>
{% endblock %}

templates/user_profile.html
{% extends 'base.html' %}
{% block title %}My Account{% endblock %}
{% block content %}
	<div class="content container register">
		<div class="row">
			<div class="col s5">
				<img src="{{ page.cover.url }}" class="responsive-img">
			</div>
			<div class="col s6 offset-l1">
			   <form class="col s12" id ="multipart" action = "/account/profile/" enctype="multipart/form-data" method="POST">
			      {% csrf_token %}
			      <div class="row">
			        <div class="input-field col s12">
			          <div class="label" >Username</div>
			          <input disabled id="id_username" name = "username" type="text" class="validate" value = "{{ user.username|default_if_none:"" }}">
			        </div>
			        	{{ user_form.username.errors }}
			        
			      </div>
			      <div class="row">
			        <div class="input-field col s12">
			          <div class="label" >Password</div>
			          <input id="id_password" name = "password" type="password" class="validate">
			        </div>
			         {{ user_form.password.errors }}
			      </div>
			      <div class="row">
			        <div class="input-field col s12">
			          <div class="label" >E-mail</div> 
			          <input id="id_email" type="email" name = "email" class="validate" value = "{{ user.email|default_if_none:"" }}">
			        </div>
			        {{ user_form.email.errors }}
			      </div>
			      <div class="row">
			        <div class="input-field col s12">
			          <div class="label" >Kids'names</div>
			          <input id="id_kidsname" type="text" name = "kidsname" class="validate" value = "{{ member.kidsname|default_if_none:"" }}">
			        </div>
			      </div>
			      <div class="row">
			        <div class="input-field col s12">
			          <div class="label" >Friend's E-mail</div>
			          <input id="id_email1" type="email" name = "email1" class="validate" placeholder = 'Let your friends make your wish come true' value = "{{ member.email1|default_if_none:"" }}">
			        </div>
			        {{ member_form.email1.errors }}
			      </div>
			      <div class="row">
			        <div class="input-field col s12">
			          <div class="label" >Address</div>
			          <textarea id="id_address" name = "address" class="materialize-textarea" class='validate' >{{ member_form.address.value|default_if_none:"" }}</textarea>
			        </div>
			      </div>
			      <div class="row right">
			      	<input type = "submit" class="btn btn-large btn-reverse" id = "submit" value = "SUBMIT" />
			      </div>
			    </form>
			</div>
		</div>
	</div>
{% endblock %}

templates/wishlist.html
{% extends "base.html" %}
{% block title %}Wish Wall{% endblock %}
{% block css %}
  <style>
    /**
     * Grid items
     */
    .tiles-wrap{
    	position: relative;
    	margin: 10px 0px;
    }
    .tiles-wrap>li {
      -moz-box-sizing: border-box;
           box-sizing: border-box;
    }
    .tiles-wrap li img {
      width: 100%;
      height: auto;
    }
  </style>
{% endblock %}
{% block content %}
<main>
	<div class="content container wishlist">
    <h3>Make A Wish</h3>
    <div class="row">
      <div class="col s6 cover">
        <img src="{{ page.cover.url }}" class="responsive-img">
      </div>
      <div class="col s6 text">     
At Ma Belle Epoque, we really cherish our customer's opinion and we would love to know what outfits you preferred most.
If you are to have a baby and don't want to be too specific about what your birth list will look like, make a wish on our website and we will invite your friends to our website to have a quick look at it and delight you with the best gifts for your newborn!
Let us take take care of the rest.
      </div>
    </div>
    <div class="row">
			<ul  class="tiles-wrap">
				{% for p in products %}
		        <li class="tile">
		        	{% if p.wishes.all %}
		        	<a><img class="hoverable" src="{{ p.image1.url }}"></a>
	        		<ul>
	        			<li><i class="fa fa-heart"></i></li>
	        			{% for w in p.wishes.all %}
	        			{% if forloop.last %}
	        			<li>{{ w.user.username }}</li>
	        			{% else %}
	        			<li>{{ w.user.username }},&nbsp;</li>
	        			{% endif %}
	        			{% endfor %}
	        		</ul>
	        		{% endif %}
		        </li>
		        {% endfor %}
			</ul>
      </div>
</main>
{% endblock %}
{% block js %}
<script type="text/javascript" src="/static/mbe/js/jquery.wookmark.min.js"></script>
<script type="text/javascript" src="/static/mbe/js/jquery.imagesloaded.js"></script>
  <script type="text/javascript">
    (function() {
      function getWindowWidth() {
        return Math.max(document.documentElement.clientWidth, window.innerWidth || 0)
      }
      // Instantiate wookmark after all images have been loaded
      var wookmark;
      imagesLoaded('.tiles-wrap', function() {
        wookmark = new Wookmark('.tiles-wrap', {
          itemWidth: 300, // Optional min width of a grid item
          outerOffset: 20, // Optional the distance from grid to parent
          flexibleWidth: function () {
            // Return a maximum width depending on the viewport
            return getWindowWidth() < 1024 ? '100%' : '50%';
          }
        });
      });
    })();
  </script>
{% endblock %}